### ISSUE TITLE
精度

### ISSUE THREAD

**Issue by hlr7999** [xcyao00/FOD#3]
您好，我跑您的代码精度没有论文里高，大概是这样的
```
Mean Image-AUC: 0.974334492926727
Mean Pixel-AUC: 0.9817032875158126
```
想请教下是什么原因呢，因为 backbone 不同吗？

**Comment by xcyao00** [comment]
请问你使用的是什么backbone, 我们测试了efficientnet-b6和wide-resnet50, 应该是可以达到论文的精度的。你可以看看是否是按照readme中的步骤运行的，是否有修改什么配置。也有可能是batch_size的问题，我们batch_size设置为1，请问你设置了怎样的batch_size。

**Comment by hlr7999** [comment]
我应该只改了 batch size，对指标影响这么大吗。还有我想问下 efficientnet-b6 和 wide-resnet50 区别大吗，我用的是 wide-resnet50。

**Comment by xin94wang** [comment]
> 我应该只改了 batch size，对指标影响这么大吗。还有我想问下 efficientnet-b6 和 wide-resnet50 区别大吗，我用的是 wide-resnet50。

您好，请问您最终训练后通过得到的权重文件进行test，mvtec数据集得到了论文中的结果吗？我的Mean Image-AUC始终在0.975左右徘徊
